FROM node:18.16-bullseye-slim

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
#COPY .npmrc /home/
COPY package*.json /usr/src/app/

RUN cd /usr/src/app/
RUN npm install
#RUN --mount=type=secret,id=npmrc,target=/home/.npmrc,mode=0755 npm install --verbose

# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . /usr/src/app/
EXPOSE 8000
CMD [ "npm", "start" ]
